version: '3.5'

# 6100 auth
# 6101 - db_auth
# 6200 data
# 6201 - db_data

services:

  auth:
    build: ./auth
    container_name: auth
    restart: on-failure
    environment:
      - SECRET_KEY=SECRET_KEY
      - PORT=6100
      - DB_USERNAME=admin
      - DB_PASSWORD=Gaz12345!auth
      - DB_HOST=db_auth_npk
      - DB_PORT=6101
      - DB_NAME=postgres
      - ACCESS_HOURS=12
    depends_on:
      - db_auth_npk
    networks:
      - internal_net

  db_auth_npk:
    restart: on-failure
    container_name: db_auth_npk
    ports:
      - "6101:6101"
    environment:
      - POSTGRES_PASSWORD=Gaz12345!auth
      - POSTGRES_USER=admin
    image: postgres:14.3-alpine
    command:
      - "postgres"
      - "-c"
      - "port=6101"
    volumes:
      - db_auth_npk_vol:/var/lib/postgresql/data
    networks:
      - internal_net
  
  
  nginx:
    restart: on-failure
    container_name: nginx
    image: nginx:1.23.1-alpine
    networks:
      - internal_net
    ports:
      - 80:80
    depends_on:
      - auth
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_auth_npk_vol: {}
  auth_vol: {}

networks:
  internal_net:
    driver: bridge